#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

"""Generate the WIT reference from `wit/` into Markdown (`DOC-017`).

Every interface, its types, its error variants, and every exported function — with the
doc comments from the WIT source preserved.

# Why generated

The `.wit` files are the **published artifact** (`qqq-abi` embeds them at compile time),
so a hand-written reference is a second copy of an interface that already exists. When
they disagree, the WIT is right and the reference is a trap — a reader who follows it
writes code that does not compile, or worse, code that compiles against a signature the
runtime does not have.

# What is extracted, and what is deliberately not

Extracted: packages, interfaces, doc comments, function signatures, and error variants.
That is what a caller needs.

**Not extracted: per-language examples.** `DOC-017` asks for them, and generating them
honestly is not possible here: a Rust example must be compiled to know it works, and
this repo has no `qqq-abi` consumer to compile against yet. A generator emitting
unverified examples would produce documentation that *looks* tested and is not, which is
worse than omitting the section. The generated page says so explicitly and names what
would make it possible.

Usage:
    python tools/gen_wit_reference.py           # write docs/wit-reference.md
    python tools/gen_wit_reference.py --check   # fail if it is out of date
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIT_DIR = ROOT / "wit"
TARGET = ROOT / "docs" / "wit-reference.md"

HEADER = """\
<!--
  GENERATED FILE -- DO NOT EDIT BY HAND.

  Source:       wit/*.wit
  Generated by: python tools/gen_wit_reference.py
  Verified by:  python tools/check_wit_reference.py  (runs in CI)

  Edit the `.wit` files instead. The interfaces there are the published artifact:
  `qqq-abi` embeds them at compile time, so a reference that disagrees with them is
  wrong and the WIT is right.
-->

# WIT reference

Every QQQ interface, generated from the `.wit` files in [`wit/`](../wit). The WIT is the
**published artifact**; this page is a rendering of it, not a second definition.

## What this page does not contain

`DOC-017` asks for per-language examples. This generator does **not** emit them, and the
reason is worth stating rather than hiding: a Rust or TypeScript example is only known
to be correct once it compiles against the real bindings, and there is no `qqq-abi`
consumer to compile against yet.

An example that cannot be built is documentation that *looks* verified. So the section
is absent rather than plausible, and it lands when `ABI-*` provides a consumer to
compile the examples in CI.

"""


def strip_doc(lines: list[str]) -> str:
    """Join `///` doc lines into one paragraph-per-blank-line string.

    A blank `///` line starts a new paragraph, which is preserved so the generated
    Markdown keeps the shape the WIT author wrote.
    """
    out: list[str] = []
    for line in lines:
        text = line.strip()
        text = text[3:] if text.startswith("///") else text
        out.append(text.strip())
    # Collapse the leading/trailing blanks, keep interior ones as paragraph breaks.
    while out and not out[0]:
        out.pop(0)
    while out and not out[-1]:
        out.pop()
    return "\n".join(out)


def parse_wit(path: Path) -> dict[str, object]:
    """Parse one `.wit` file into a package record."""
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    package = None
    file_doc: list[str] = []
    interfaces: list[dict[str, object]] = []

    current: dict[str, object] | None = None
    doc: list[str] = []
    funcs: list[dict[str, object]] = []
    types: list[dict[str, object]] = []
    pending_doc: list[str] = []

    # # Why brace depth is tracked rather than matching `}` at column 0
    #
    # The first version ended an interface on any line whose stripped form was `}`.
    # But `record`, `enum` and `variant` blocks nest *inside* an interface, so the
    # first nested closing brace ended the interface early — and every function
    # declared after it vanished. The generated reference showed
    # `qqq:http@1.0.0 http` with **0 functions** when it exports `send`,
    # `send-streaming` and `incoming-authority`.
    #
    # The output looked plausible, which is what made it dangerous: a reference that
    # silently omits three of an interface's four functions is worse than one that
    # fails to generate. Tracked by depth, the interface ends only at its own brace.
    depth = 0
    in_interface = False

    def flush_func(raw: str) -> None:
        # `name: func(params) -> result;` possibly with an `@since` attribute above.
        m = re.match(
            r"\s*([a-z][a-z0-9-]*)\s*:\s*(?:async\s+)?func\s*(\(.*?\))\s*(->\s*(.+?))?\s*;",
            raw,
        )
        if not m:
            return
        funcs.append(
            {
                "name": m.group(1),
                "params": m.group(2).strip(),
                "result": (m.group(4) or "").strip(),
                "doc": strip_doc(pending_doc),
            }
        )
        pending_doc.clear()

    for raw in lines:
        stripped = raw.strip()

        if stripped.startswith("package "):
            package = stripped.rstrip(";").replace("package ", "").strip()
            continue

        m_iface = re.match(r"^interface\s+([a-z][a-z0-9-]*)\s*\{", stripped)
        if m_iface and not in_interface:
            current = {"name": m_iface.group(1), "doc": strip_doc(doc)}
            doc = []
            in_interface = True
            depth = 1
            continue

        if stripped.startswith("///"):
            pending_doc.append(raw)
            if current is None:
                doc.append(raw)
            continue

        if stripped.startswith("//") or stripped.startswith("#") or not stripped:
            if not stripped and current is None:
                doc.append("")
            continue

        if not in_interface:
            continue

        # # Why `pending_doc` is cleared when a nested block OPENS
        #
        # The docs for a `variant`'s cases sit between the variant's opening brace and
        # its close, and the first version left them pending — so `resource directory`
        # inherited the last error variant's text as its own description:
        #
        #     * `resource directory` — 7 method(s)
        #       `fs.read` or `fs.write` was not granted.      <- an error case, not the
        #                                                        resource's doc
        #
        # The resource's real doc ("A handle to an open directory") was correct and
        # two lines above; the parser simply appended the wrong paragraph to it. A
        # doc block belongs to the declaration that follows it, and a nested block
        # ends that association.
        #
        # Any other `{` deepens the nesting; a `}` shallows it. The interface ends
        # only when its OWN brace closes, which is depth reaching zero.
        opens = stripped.count("{")
        closes = stripped.count("}")

        # A type or function declaration is interesting at depth 1, where the
        # interface's own members live, AND at depth 2, where a `resource` block's
        # methods live.
        #
        # # Why depth 2 matters, found by looking at the zero-function interface
        #
        # `qqq:fs@1.0.0 filesystem` reported **0 functions** after the brace-depth fix,
        # which looked like an interface that exports nothing. Reading the WIT showed
        # the opposite: it exports `open-subdirectory`, `read-file`, `write-file` and
        # more, all as methods inside `resource directory { ... }`.
        #
        # A resource's methods are the interface's public API — a guest calls them on
        # a handle. Omitting them would have produced a reference for the filesystem
        # interface that listed no way to use the filesystem. The generated page looks
        # equally plausible either way, which is why this was worth chasing rather than
        # accepting.
        if depth in (1, 2):
            m_type = re.match(
                r"^(record|enum|variant|flags|type|resource)\s+([a-z][a-z0-9-]*)", stripped
            )
            if m_type:
                types.append(
                    {
                        "kind": m_type.group(1),
                        "name": m_type.group(2),
                        "doc": strip_doc(pending_doc),
                        "methods": [],
                    }
                )
                pending_doc.clear()
            elif ": func" in stripped:
                # At depth 2 this is a resource method, recorded against the resource
                # so the reference can show it under its owner rather than loose.
                if depth == 2 and types and types[-1]["kind"] == "resource":
                    m = re.match(
                        r"\s*([a-z][a-z0-9-]*)\s*:\s*(?:async\s+)?func\s*(\(.*?\))\s*"
                        r"(->\s*(.+?))?\s*;",
                        raw,
                    )
                    if m:
                        types[-1]["methods"].append(  # type: ignore[union-attr]
                            {
                                "name": m.group(1),
                                "params": m.group(2).strip(),
                                "result": (m.group(4) or "").strip(),
                                "doc": strip_doc(pending_doc),
                            }
                        )
                        pending_doc.clear()
                else:
                    flush_func(raw)

        # `@since(...)` and other attributes carry no braces, so they need no branch.
        depth += opens - closes

        # A block boundary ends whatever doc was pending: an opening brace consumed it
        # for the declaration itself, and a closing brace ends a nested block whose
        # inner docs (a variant's cases) must not leak to the next sibling.
        if opens or closes:
            pending_doc.clear()

        if depth <= 0:
            current["functions"] = funcs
            current["types"] = types
            interfaces.append(current)
            current = None
            funcs = []
            types = []
            in_interface = False
            pending_doc.clear()

    return {
        "file": path.name,
        "package": package,
        "doc": strip_doc(file_doc) if file_doc else "",
        "interfaces": interfaces,
    }


def render(records: list[dict[str, object]]) -> str:
    """Render the reference markdown."""
    parts = [HEADER]

    total_ifaces = sum(len(r["interfaces"]) for r in records)  # type: ignore[arg-type]
    total_funcs = sum(
        len(i["functions"])  # type: ignore[arg-type]
        for r in records
        for i in r["interfaces"]  # type: ignore[union-attr]
    )
    parts.append(
        f"**{len(records)} package(s), {total_ifaces} interface(s), {total_funcs} "
        f"function(s).**\n"
    )

    parts.append("## Interfaces\n")
    parts.append("| Package | Interface | Functions |")
    parts.append("|---|---|---|")
    for r in records:
        for i in r["interfaces"]:  # type: ignore[union-attr]
            parts.append(
                f"| `{r['package']}` | [`{i['name']}`](#{str(r['package']).replace(':', '').replace('@', '').replace('.', '')}-{i['name']}) | {len(i['functions'])} |"  # type: ignore[arg-type]
            )
    parts.append("")

    for r in records:
        parts.append(f"## Package `{r['package']}`\n")
        parts.append(f"Source: [`wit/{r['file']}`](../wit/{r['file']})\n")
        if r["doc"]:
            parts.append(f"{r['doc']}\n")

        for i in r["interfaces"]:  # type: ignore[union-attr]
            parts.append(f"### `{i['name']}`\n")
            if i["doc"]:
                parts.append(f"{i['doc']}\n")

            if i["types"]:  # type: ignore[arg-type]
                parts.append("**Types**\n")
                for t in i["types"]:  # type: ignore[union-attr]
                    methods = t.get("methods") or []  # type: ignore[union-attr]
                    suffix = f" — {len(methods)} method(s)" if methods else ""
                    parts.append(f"* `{t['kind']} {t['name']}`{suffix}")
                    if t["doc"]:
                        first = str(t["doc"]).split("\n")[0]
                        parts.append(f"  {first}")
                    for m in methods:  # type: ignore[union-attr]
                        ret = f" → `{m['result']}`" if m["result"] else ""
                        parts.append(f"    * `{m['name']}{m['params']}`{ret}")
                parts.append("")

            if i["functions"]:  # type: ignore[arg-type]
                parts.append("**Functions**\n")
                for f in i["functions"]:  # type: ignore[union-attr]
                    return_part = f" → `{f['result']}`" if f["result"] else ""
                    parts.append(f"* `{f['name']}{f['params']}`{return_part}")
                    if f["doc"]:
                        first = str(f["doc"]).split("\n")[0]
                        parts.append(f"  {first}")
                parts.append("")
            elif not i["types"]:  # type: ignore[arg-type]
                parts.append("*This interface exports no functions or types.*\n")

    parts.append(
        "---\n\n"
        "## Regenerating\n\n"
        "```\npython tools/gen_wit_reference.py\n```\n\n"
        "`tools/check_wit_reference.py` fails CI when this page and the `.wit` files\n"
        "disagree, so a WIT change without a regeneration is caught rather than\n"
        "shipping a reference that describes the previous interface.\n"
    )
    return "\n".join(parts)


def main() -> int:
    check_only = "--check" in sys.argv

    if not WIT_DIR.is_dir():
        print(f"FATAL: {WIT_DIR} does not exist")
        return 1

    files = sorted(WIT_DIR.glob("*.wit"))
    if not files:
        print(f"FATAL: no `.wit` files in {WIT_DIR}")
        return 1

    records = [parse_wit(p) for p in files]

    # # Why an empty parse is a failure rather than an empty document
    #
    # If the parser stopped matching — a WIT syntax change, a moved directory — every
    # record would have zero interfaces, and the generated page would be a valid
    # Markdown file saying nothing. The check would then agree with it, because both
    # would be empty. That is the failure this guard prevents.
    total_ifaces = sum(len(r["interfaces"]) for r in records)  # type: ignore[arg-type]
    if total_ifaces == 0:
        print(
            "FATAL: parsed 0 interfaces from "
            f"{len(files)} file(s). The parser is not matching the WIT syntax, and an "
            "empty reference would pass any check that compares it to itself."
        )
        return 1

    generated = render(records)

    if check_only:
        if not TARGET.exists():
            print(f"FATAL: {TARGET} does not exist; run tools/gen_wit_reference.py")
            return 1
        current = TARGET.read_text(encoding="utf-8")
        if current != generated:
            print(
                "FATAL: docs/wit-reference.md is out of date with wit/. Run "
                "`python tools/gen_wit_reference.py`."
            )
            for i, (a, b) in enumerate(
                zip(current.splitlines(), generated.splitlines()), start=1
            ):
                if a != b:
                    print(f"  first difference at line {i}:")
                    print(f"    committed: {a[:110]}")
                    print(f"    generated: {b[:110]}")
                    break
            else:
                print(
                    f"  the committed file has {len(current.splitlines())} lines and "
                    f"the generated one has {len(generated.splitlines())}"
                )
            return 1
        print(
            f"WIT REFERENCE OK -- {len(files)} package(s), {total_ifaces} interface(s), "
            f"matches wit/"
        )
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} with {total_ifaces} interface(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
