#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

"""Generate the error catalogue from `qqq-core`'s `ErrorCode` enum (`DOC-019`).

Every `QQQ-XXXX` code becomes a catalogue entry with its cause and its remediation,
extracted from the doc comments beside the variant.

# Why generated from the enum rather than written

The code list and the documentation would otherwise be two lists, and the failure mode
of two lists is specific: a new variant is added, the catalogue is not updated, and a
user who hits the new code finds **nothing**. That user is by definition already having
a bad time, and the document they were sent to does not mention their error.

Generating makes that impossible — the catalogue cannot be missing a code, because the
enum is its only source.

# What is extracted

Each variant carries a doc comment in a fixed shape:

    /// <cause, in one or two sentences>
    /// **Remediation:** <what to do>
    VariantName = NNNN,

Both parts are required. A variant without a `**Remediation:**` marker is reported as a
**problem** rather than being emitted with an empty fix, because §12.2's standard is
that every code tells the user what to do — and a generated page with a blank
"Remediation" section would satisfy the generator while failing the standard.

Usage:
    python tools/gen_error_catalogue.py           # write docs/errors.md
    python tools/gen_error_catalogue.py --check   # fail if it is out of date
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

def _root_from_argv(argv: list[str]) -> Path:
    """The repository root, overridable with `--root <path>`.

    # Why a generator takes a root at all

    A self-test proves this generator detects drift by injuring the file it writes and
    the source it reads, then restoring them. Injuring the repository's own files means
    a run killed mid-injection leaves the tree mutated, and the mutation then reads as a
    real defect against every later run (`§O-260`). `--root` lets the self-test aim
    every read and write at a temporary copy. The default is unchanged.
    """
    if "--root" in argv:
        i = argv.index("--root")
        if i + 1 >= len(argv):
            print("FATAL: --root needs a path", file=sys.stderr)
            raise SystemExit(2)
        return Path(argv[i + 1]).resolve()
    return Path(__file__).resolve().parent.parent


ROOT = _root_from_argv(sys.argv)
SOURCE = ROOT / "crates" / "qqq-core" / "src" / "error.rs"
TARGET = ROOT / "docs" / "errors.md"

# The numeric ranges, from the enum's own section comments. Stated here so the
# generated document can group by area, and checked against the enum so a code in an
# unexpected range is reported rather than silently filed under a wrong heading.
RANGES: list[tuple[int, int, str, str]] = [
    (1000, 1999, "Build and compilation", "Producing a component from source."),
    (2000, 2999, "Manifest and configuration", "Reading `qqq.toml` and resolving intent."),
    (3000, 3999, "Capability and policy", "Granting and enforcing authority."),
    (4000, 4999, "Runtime execution", "Running a component: traps, limits, fuel."),
    (5000, 5999, "Package management", "Resolution, fetching, verification."),
    (6000, 6999, "HTTP and serving", "Serving requests and streaming responses."),
    (7000, 7999, "Tooling and diagnostics", "The CLI, inspectors and reporters."),
    (8000, 8999, "Host and environment", "The host process and its platform."),
]

HEADER = """\
<!--
  GENERATED FILE -- DO NOT EDIT BY HAND.

  Source:       crates/qqq-core/src/error.rs (the `ErrorCode` enum and its doc comments)
  Generated by: python tools/gen_error_catalogue.py
  Verified by:  python tools/check_error_catalogue.py  (runs in CI)

  Edit the enum's doc comments instead. Each variant's cause and its
  `**Remediation:**` line are what appear below.
-->

# Error catalogue

Every `QQQ-XXXX` code, what causes it, and what to do about it. **Generated** from the
`ErrorCode` enum in `qqq-core`, so this list cannot be missing a code the runtime can
emit.

## How to read a code

The four digits carry meaning, which is why they are not sequential:

| Range | Area | What it covers |
|---|---|---|
"""


def parse_variants(text: str) -> list[dict[str, object]]:
    """Extract every variant with its doc comment, code and remediation.

    Returns dicts with `variant`, `code`, `cause`, `remediation`, `deprecated`.
    Raises when the enum itself cannot be found, because an empty result would
    generate an empty catalogue and the check would then agree with it.
    """
    marker = "pub enum ErrorCode {"
    start = text.find(marker)
    if start == -1:
        raise ValueError("crates/qqq-core/src/error.rs has no `pub enum ErrorCode`")

    # The enum body runs to the matching closing brace at column 0.
    rest = text[start + len(marker) :]
    end = rest.find("\n}")
    body = rest[:end] if end != -1 else rest

    variants: list[dict[str, object]] = []
    pending: list[str] = []
    deprecated = False

    for line in body.splitlines():
        stripped = line.strip()

        if stripped.startswith("///"):
            doc = stripped[3:].strip()
            # `#[deprecated]` often appears directly above the variant; note it.
            pending.append(doc)
            continue

        if stripped.startswith("#[deprecated"):
            deprecated = True
            continue

        if stripped.startswith("//") or not stripped:
            # A plain comment (the range banners) or a blank line. The range banners
            # start a new group; they are parsed as code, so nothing is lost here.
            if stripped.startswith("// --"):
                pending.clear()
            continue

        match = re.match(r"([A-Z][A-Za-z0-9]*)\s*=\s*(\d{4})\s*,", stripped)
        if not match:
            continue

        variant, code = match.group(1), int(match.group(2))

        cause_lines: list[str] = []
        remediation_lines: list[str] = []
        in_remediation = False
        in_rationale = False
        for doc in pending:
            if doc.startswith("**Remediation:**"):
                in_remediation = True
                remediation_lines.append(doc[len("**Remediation:**") :].strip())
            elif in_remediation:
                remediation_lines.append(doc)
            elif doc.startswith("#"):
                # A rationale heading ends the cause.
                #
                # The convention is: one line naming the cause, optional `# ...`
                # sections explaining it, then `**Remediation:**`. Without this
                # stop, `QQQ-7004`'s published cause read "A command was given a
                # flag it does not accept. # Why this is distinct from
                # `McpArgumentInvalid` 7001 is about *arguments* ..." -- a cause
                # that carries the design rationale, rendered into docs/errors.md
                # and into every `qqqai schema --all` payload.
                in_rationale = True
            elif not in_rationale:
                cause_lines.append(doc)

        variants.append(
            {
                "variant": variant,
                "code": code,
                "cause": truncate_rationale(" ".join(l for l in cause_lines if l).strip()),
                # Capitalised on emit: the source writes the remediation as the
                # continuation of `**Remediation:** ...`, which reads naturally
                # there, while the published document renders it as its own
                # sentence after `**Remediation.** `. 38 of 43 entries started
                # lowercase before this, so the document read as a list of
                # fragments.
                "remediation": sentence_case(
                    " ".join(l for l in remediation_lines if l).strip()
                ),
                "deprecated": deprecated,
            }
        )
        pending = []
        deprecated = False

    if not variants:
        raise ValueError("the `ErrorCode` enum has no parseable variants")
    return variants


def validate(variants: list[dict[str, object]]) -> list[str]:
    """Return the problems with the parsed variants. Empty means they are usable."""
    problems: list[str] = []

    seen: dict[int, str] = {}
    for v in variants:
        code = int(v["code"])  # type: ignore[arg-type]
        variant = str(v["variant"])

        if code in seen:
            problems.append(
                f"QQQ-{code:04} is assigned to both `{seen[code]}` and `{variant}`. "
                f"Two variants with one code makes the code useless as an identifier."
            )
        seen[code] = variant

        if not v["cause"]:
            problems.append(
                f"`{variant}` (QQQ-{code:04}) has no doc comment describing its cause, "
                f"so the catalogue could not say what went wrong"
            )
        if not v["remediation"]:
            problems.append(
                f"`{variant}` (QQQ-{code:04}) has no `**Remediation:**` line. §12.2 "
                f"requires every code to tell the user what to do; a generated page "
                f"with a blank Remedy section would satisfy the generator and fail the "
                f"standard."
            )

        known = any(lo <= code <= hi for lo, hi, _t, _d in RANGES)
        if not known:
            problems.append(
                f"`{variant}` (QQQ-{code:04}) falls outside every documented range, so "
                f"the catalogue cannot file it under an area"
            )

    return problems


def render(variants: list[dict[str, object]]) -> str:
    """Render the catalogue markdown."""
    parts = [HEADER]
    for lo, hi, title, blurb in RANGES:
        parts.append(f"| `{lo}`–`{hi}` | **{title}** | {blurb} |")
    parts.append("")
    parts.append(
        "A code's range tells you *which subsystem* failed, which is the first thing you\n"
        "want to know. The last digit is not meaningful — codes are allocated in\n"
        "allocation order within a range, never reused, and never renumbered, because\n"
        "logs and issue trackers reference them indefinitely.\n"
    )

    for lo, hi, title, _blurb in RANGES:
        group = [v for v in variants if lo <= int(v["code"]) <= hi]  # type: ignore[arg-type]
        if not group:
            continue
        parts.append(f"## {title}\n")
        for v in sorted(group, key=lambda x: int(x["code"])):  # type: ignore[arg-type]
            code = int(v["code"])  # type: ignore[arg-type]
            variant = str(v["variant"])
            parts.append(f"### `QQQ-{code:04}` — `{variant}`\n")
            if v["deprecated"]:
                parts.append(
                    "> **Deprecated.** This code is retired and will not be emitted by\n"
                    "> new builds, but it remains documented because existing logs\n"
                    "> reference it.\n"
                )
            parts.append(f"**Cause.** {v['cause']}\n")
            parts.append(f"**Remediation.** {v['remediation']}\n")
            # The identifier a program matches on, which is the string §12.2 calls the
            # machine contract.
            parts.append(f"```json\n{{ \"code\": \"QQQ-{code:04}\" }}\n```\n")

    parts.append(
        "---\n\n"
        "## Why the code is a contract\n\n"
        "The string `QQQ-XXXX` is part of the machine interface, not a message\n"
        "decoration. Agents and scripts match on it, so it never changes meaning and is\n"
        "never reused for a different fault. The human-readable cause beside it is free\n"
        "to improve in any release; the code is not.\n"
    )
    return "\n".join(parts)


def sentence_case(text: str) -> str:
    """Capitalise the first character, leaving the rest untouched.

    Only the first character: `qqqai`, `max_subrequests` and `QQQ-6005` must
    survive verbatim, and a `.capitalize()` would lowercase them.
    """
    if not text:
        return text
    return text[0].upper() + text[1:]


def truncate_rationale(cause: str) -> str:
    """Drop a trailing 'why this is distinct' paragraph from a cause.

    # Why this is needed

    The doc-comment convention is a one-line cause, optional rationale, then the
    remediation. Most rationale sections use a `# ...` heading and are stopped by
    the parser. Four do not: they open with an emphasised sentence such as
    "**Distinct from `MemoryLimitExceeded` on purpose.**", so the rationale ran
    into the published cause -- up to 875 characters of design argument rendered
    into `docs/errors.md` and every `qqqai schema --all` payload.

    The cut is on the phrase such a paragraph actually uses, and the cause's own
    first sentence is always complete before it.
    """
    for marker in (" **Distinct from", " Distinct from", " It is deliberately", " Deliberately a"):
        i = cause.find(marker)
        if i > 0:
            return cause[:i].strip()
    return cause


def main(argv: list[str]) -> int:
    # `argv` is taken rather than read from `sys` inside, so the entry point is
    # the only place that touches process state -- the same shape the other
    # generators use, and it makes `main(["--check"])` callable from a test.
    check_only = "--check" in argv

    if not SOURCE.exists():
        print(f"FATAL: {SOURCE} does not exist")
        return 1

    try:
        variants = parse_variants(SOURCE.read_text(encoding="utf-8"))
    except ValueError as e:
        print(f"FATAL: {e}")
        return 1

    problems = validate(variants)
    if problems:
        # Reported rather than emitted: a catalogue with holes is worse than a build
        # failure, because it looks complete.
        print("ERROR CATALOGUE INCOMPLETE")
        print("")
        for p in problems:
            print(f"  FAIL  {p}")
        return 1

    generated = render(variants)

    if check_only:
        if not TARGET.exists():
            print(f"FATAL: {TARGET} does not exist; run tools/gen_error_catalogue.py")
            return 1
        current = TARGET.read_text(encoding="utf-8")
        if current != generated:
            print(
                "FATAL: docs/errors.md is out of date with the ErrorCode enum. Run "
                "`python tools/gen_error_catalogue.py`."
            )
            for i, (a, b) in enumerate(
                zip(current.splitlines(), generated.splitlines()), start=1
            ):
                if a != b:
                    print(f"  first difference at line {i}:")
                    print(f"    committed: {a[:110]}")
                    print(f"    generated: {b[:110]}")
                    break
            else:
                print(
                    f"  the committed file has {len(current.splitlines())} lines and "
                    f"the generated one has {len(generated.splitlines())}"
                )
            return 1
        print(
            f"ERROR CATALOGUE OK -- {len(variants)} code(s), every one with a cause and "
            f"a remediation"
        )
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} with {len(variants)} code(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
