#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

"""Generate `docs/glossary.md` from the Proposal's §0.6 glossary table (`DOC-011`).

# Why generated rather than written

The Proposal's §0.6 table is normative: "Where a term is contested in the industry,
the definition here wins for this project." A hand-maintained copy drifts from it, and
the drift is invisible — both documents read as authoritative, and a reader has no way
to tell which is stale.

Generating removes the possibility. `tools/check_glossary.py` then verifies the
committed file matches its source, so a hand-edit fails CI rather than being silently
reverted by the next generation.

# What is preserved

The *order* of the Proposal's rows and their exact wording. Reordering would make a
diff against the Proposal unreadable, and rewording would introduce a second
authority for the same term.

Usage:
    python tools/gen_glossary.py           # write docs/glossary.md
    python tools/gen_glossary.py --check   # fail if it is out of date
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROPOSAL = ROOT / "QQQ-Proposal-V1.md"
GLOSSARY = ROOT / "docs" / "glossary.md"

# The generated header. `DO NOT EDIT` is stated first because the most common way a
# generated file breaks is a well-meaning edit that the next run discards.
HEADER = """\
<!--
  GENERATED FILE -- DO NOT EDIT BY HAND.

  Source:      QQQ-Proposal-V1.md, section §0.6 (the glossary table)
  Generated by: python tools/gen_glossary.py
  Verified by:  python tools/check_glossary.py  (runs in CI)

  Edit the Proposal's table instead. `check_glossary.py` fails the build when this
  file and its source disagree, so a hand-edit here is caught rather than silently
  reverted by the next generation.
-->

# Glossary

Every term QQQ uses precisely. This is **generated** from the Proposal's §0.6 table,
which is normative: where a term is contested in the industry, the definition there
wins for this project.

Each entry links to its anchor in the Proposal, so a reader can see the term in
context rather than only in isolation.

"""


def github_anchor(heading: str) -> str:
    """Derive a GitHub-flavoured anchor from a heading, as §0.5 specifies.

    `## §6.4 Capability Engine` → `#64-capability-engine`

    The rules: drop the `§`, lowercase, remove punctuation except hyphens and
    underscores, and replace spaces with hyphens. Stated here rather than assumed,
    because the Proposal §0.5 pins this derivation and `DOC-008` documents it.
    """
    text = heading.strip()
    text = text.lstrip("#").strip()
    text = text.replace("§", "")
    text = text.lower()
    # Keep alphanumerics, spaces, hyphens and underscores; drop the rest.
    text = re.sub(r"[^\w\s-]", "", text)
    return text.strip().replace(" ", "-")


def parse_glossary_table(text: str) -> list[tuple[str, str]]:
    """Extract `(term, definition)` rows from the Proposal's §0.6 table.

    Returns rows in document order. Raises when the section or its table is missing,
    because a silent empty result would generate an empty glossary and the check
    would then agree with it — two documents confidently saying nothing.
    """
    marker = "## §0.6 Glossary"
    start = text.find(marker)
    if start == -1:
        raise ValueError("the Proposal has no `## §0.6 Glossary` section")

    # The section runs to the next `## ` heading at the same level.
    rest = text[start + len(marker) :]
    nxt = re.search(r"(?m)^## ", rest)
    section = rest[: nxt.start()] if nxt else rest

    rows: list[tuple[str, str]] = []
    for line in section.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        if len(cells) < 2:
            continue
        term, definition = cells[0], cells[1]
        # Skip the header row and the separator row.
        if term.lower() == "term":
            continue
        if set(term) <= set("-: "):
            continue
        rows.append((term, definition))

    if not rows:
        raise ValueError("the §0.6 table has no data rows")
    return rows


def render(rows: list[tuple[str, str]]) -> str:
    """Render the glossary markdown."""
    parts = [HEADER]
    for term, definition in rows:
        # The Proposal writes terms as `**Bold**`; strip the markers for the anchor
        # derivation but keep the plain name in the heading, so the generated file
        # does not nest bold inside a heading.
        plain = term.strip("*").strip()
        parts.append(f"## {plain}\n")
        parts.append(f"{definition}\n")
        parts.append(
            f"[→ Proposal §0.6]({PROPOSAL_NAME}#{github_anchor('## §0.6 Glossary')})\n"
        )
    return "\n".join(parts)


PROPOSAL_NAME = "../QQQ-Proposal-V1.md"


def main() -> int:
    check_only = "--check" in sys.argv

    if not PROPOSAL.exists():
        print(f"FATAL: {PROPOSAL} does not exist")
        return 1

    try:
        rows = parse_glossary_table(PROPOSAL.read_text(encoding="utf-8"))
    except ValueError as e:
        print(f"FATAL: {e}")
        return 1

    generated = render(rows)

    if check_only:
        if not GLOSSARY.exists():
            print(f"FATAL: {GLOSSARY} does not exist; run tools/gen_glossary.py")
            return 1
        current = GLOSSARY.read_text(encoding="utf-8")
        if current != generated:
            print(
                "FATAL: docs/glossary.md is out of date with the Proposal's §0.6 "
                "table. Run `python tools/gen_glossary.py`."
            )
            # Report the first differing line, so the reader does not have to diff
            # two long documents by eye.
            for i, (a, b) in enumerate(
                zip(current.splitlines(), generated.splitlines()), start=1
            ):
                if a != b:
                    print(f"  first difference at line {i}:")
                    print(f"    committed: {a[:100]}")
                    print(f"    generated: {b[:100]}")
                    break
            else:
                print(
                    f"  the committed file has {len(current.splitlines())} lines and "
                    f"the generated one has {len(generated.splitlines())}"
                )
            return 1
        print(f"GLOSSARY OK -- {len(rows)} term(s), matches the Proposal's §0.6 table")
        return 0

    GLOSSARY.parent.mkdir(parents=True, exist_ok=True)
    GLOSSARY.write_text(generated, encoding="utf-8")
    print(f"wrote {GLOSSARY.relative_to(ROOT)} with {len(rows)} term(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
