#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""The three-document sync ritual, as one command. `PLAN-016`.

# The ritual, and why it is a tool rather than a paragraph

A change to this repository moves **derived** files, and the mapping is not obvious:

| an edit to | moves | which is regenerated by |
|---|---|---|
| a checklist status or number | `tools/backlog.json`, `llms.txt`, `llms-full.txt` | `gen_backlog.py --record`, `gen_llms_txt.py --record` |
| one of the three normative documents | `tools/corpus_at_rest.json` | `check_corpus_at_rest.py --record` |
| an observation heading | `observation-headings`, `observation-highest` in two documents | `sync_resolved_figures.py` |
| a new `docs/**/*.md` | the index needs it **curated or excluded** | `gen_llms_txt.py` |
| any `.rs` under `crates/` | `docs/unsafe-audit.md` | `audit_unsafe.py --record` |
| a figure behind a `qqq:claim` | the owning document | `sync_resolved_figures.py` |

**Every one of those is mechanical, and every one has cost a red CI run when it was missed.** This session
alone: a checklist tick moved `checklist-done` and `checklist-open` and `check_doc_claims` failed **because it
was run before the tick rather than after**; an observation landing moved two more figures; a new curated
document broke `gen_llms_txt --self-test`; and an `.rs` file moved `docs/unsafe-audit.md` twice.

# Why this runs the checkers rather than reading `git status`

**Because the staleness is defined by the checkers and by nothing else.** A tool that inspected changed paths
would be **a reimplementation of rules it does not own**, and `§O-282` is the record of what happens next: it
would be only as wide as its list of paths and only as narrow as its patterns, and the first rule it did not
know about would be a silent gap.

**So the design is the opposite: ask each checker what it thinks, regenerate only what is actually stale, and
then ask again.** **A tool that cannot be stale about its own subject**, because its subject is the checkers'
verdicts.

# Why `--record` is not in a gate

**CI must not write.** `--check` is read-only and reports; `--record` writes and is for a developer's machine.
`check_gate_parity.py` rule 5 requires every `tools/check_*.py` to be invoked in both gates, and this file is
not named `check_*` **on purpose** -- wiring a writer into a gate would be worse than the drift it prevents.

# Why every count is printed

**A tool that silently matches nothing is indistinguishable from one that finds nothing wrong.** Each step
prints how many files it examined and how many it changed, so *"nothing to do"* and *"I looked at nothing"*
cannot be confused -- which is `§O-450`'s subject seen from the tool's side.
"""

from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
PY = sys.executable

# **(name, args, what it owns).** Ordered so that a regenerator runs before the checker that judges it.
REGENERATORS: list[tuple[str, list[str], str]] = [
    (
        "sync_resolved_figures",
        [".scratch/sync_resolved_figures.py"],
        "figures behind a `qqq:claim`",
    ),
    ("gen_backlog", ["tools/gen_backlog.py", "--record"], "the machine-readable backlog"),
    ("gen_llms_txt", ["tools/gen_llms_txt.py", "--record"], "the index and the corpus"),
    (
        "check_corpus_at_rest",
        ["tools/check_corpus_at_rest.py", "--record"],
        "the three normative documents' digests",
    ),
    ("audit_unsafe", ["tools/audit_unsafe.py", "--record"], "docs/unsafe-audit.md"),
]

CHECKERS: list[tuple[str, list[str]]] = [
    ("check_checklist_counts", ["tools/check_checklist_counts.py"]),
    ("check_doc_claims", ["tools/check_doc_claims.py"]),
    ("check_xrefs", ["tools/check_xrefs.py"]),
    ("check_done_lines", ["tools/check_done_lines.py"]),
    ("check_checklist_citations", ["tools/check_checklist_citations.py"]),
    ("check_corpus_at_rest", ["tools/check_corpus_at_rest.py"]),
    ("normalize_eol", ["tools/normalize_eol.py", "--check"]),
    # **The two that a `--check` alone cannot answer.** Both have a sibling mode that runs the tool's own
    # rules against fabricated inputs, and `O-450` is the record of what happens when only the first is run.
    ("gen_llms_txt --self-test", ["tools/gen_llms_txt.py", "--self-test"]),
    ("check_done_lines --self-test", ["tools/check_done_lines.py", "--self-test"]),
]


def run(args: list[str]) -> tuple[int, str]:
    """Run one command from the repository root, returning its exit code and last non-empty line."""
    p = subprocess.run(  # noqa: S603 -- a fixed command list, not user input
        [PY, *args],
        cwd=REPO,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    tail = [l for l in (p.stdout or "").splitlines() if l.strip()]
    return p.returncode, (tail[-1] if tail else "")


def verdicts() -> list[tuple[str, int, str]]:
    out = []
    for name, args in CHECKERS:
        code, last = run(args)
        out.append((name, code, last))
    return out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="The three-document sync ritual (PLAN-016).")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true", help="report only; exit 1 if anything is stale")
    g.add_argument("--record", action="store_true", help="regenerate what is stale, then re-check")
    ap.add_argument("--self-test", action="store_true", help="prove the ritual notices a deliberate drift")
    ns = ap.parse_args(argv)

    if ns.self_test:
        return self_test()

    # **Ask first.** The checkers define staleness, so the tool starts by listening to them rather than by
    # guessing which paths changed.
    before = verdicts()
    stale = [n for n, c, _ in before if c != 0]
    print(f"  examined {len(before)} checker(s); {len(stale)} disagree(s) with the tree")
    for name, code, last in before:
        mark = "stale" if code else "OK   "
        print(f"    {mark} {name:32} {last[:96]}")

    if not stale:
        print("\nSYNC OK -- every derived file already matches the tree; nothing to regenerate")
        return 0

    if not ns.record:
        print(
            f"\nSYNC STALE -- {len(stale)} checker(s) disagree. Run `python tools/sync_docs.py --record` "
            "to regenerate the derived files, or fix the cause if the disagreement is not derived."
        )
        return 1

    # **Regenerate, and say what each step touched.** A regenerator that examined nothing must be visible,
    # because "nothing to do" and "I looked at nothing" are the same output otherwise.
    print(f"\n  regenerating through {len(REGENERATORS)} step(s):")
    for name, args, owns in REGENERATORS:
        code, last = run(args)
        print(f"    {'ok  ' if code == 0 else 'FAIL'} {name:22} {owns:44} {last[:56]}")

    after = verdicts()
    still = [n for n, c, _ in after if c != 0]
    if still:
        print(f"\nSYNC FAILED -- {len(still)} checker(s) still disagree after regenerating: {', '.join(still)}")
        print("  These are not derived-file drift; they are a defect in the tree. Fix them.")
        return 1
    print("\nSYNC OK -- regenerated, and every checker now agrees with the tree")
    return 0


def self_test() -> int:
    """Fabricate a drift in a *copy* of the tree and require the ritual to report it.

    **The copy is the point.** A self-test that edited the real tree would be a self-test that can leave the
    real tree broken, which is the shape `check_fault_inject_restores.py` exists to police elsewhere.
    """
    import shutil
    import tempfile

    cases: list[tuple[str, bool]] = []
    with tempfile.TemporaryDirectory() as tmp:
        work = pathlib.Path(tmp) / "qqq"
        shutil.copytree(REPO, work, ignore=shutil.ignore_patterns(".git", "target", "__pycache__"))

        # **Case 1: an observation heading added without recording.** The figure resolvers read the document,
        # so adding an id must move `observation-highest` and the ritual must notice.
        doc = work / "QQQ-Observations-and-Memories.md"
        text = doc.read_text(encoding="utf-8")
        marker = "*End of `QQQ-Observations-and-Memories.md`.*"
        assert marker in text, "the self-test needs the closing marker"
        injected = "## \u00a7O-" + "9999" + " \u2014 a deliberate drift"
        doc.write_text(
            text.replace(marker, injected + "\n\nBody.\n\n" + marker, 1),
            encoding="utf-8",
        )
        code, _ = run_in(work, ["tools/check_doc_claims.py"])
        cases.append(("an unrecorded observation heading is reported", code != 0))

        # **Case 2: the corpus digest is not re-recorded after a normative edit.**
        prop = work / "QQQ-Proposal-V1.md"
        prop.write_text(prop.read_text(encoding="utf-8") + "\n<!-- drift -->\n", encoding="utf-8")
        code, _ = run_in(work, ["tools/check_corpus_at_rest.py"])
        cases.append(("an unrecorded normative edit is reported", code != 0))

        # **The control.** A tree the self-test did NOT touch must still pass, or the two cases above prove
        # only that some command fails somewhere.
        code, _ = run_in(work, ["tools/check_checklist_counts.py"])
        cases.append(("an untouched checker still passes (the control)", code == 0))

    bad = [n for n, ok in cases if not ok]
    for name, ok in cases:
        print(f"  {'OK  ' if ok else 'FAIL'} {name}")
    if bad:
        print(f"\nSELF-TEST FAILED -- {len(bad)} of {len(cases)}")
        return 5
    print(f"\nSELF-TEST PASSED -- {len(cases)} of {len(cases)}")
    return 0


def run_in(cwd: pathlib.Path, args: list[str]) -> tuple[int, str]:
    p = subprocess.run(  # noqa: S603 -- a fixed command list
        [PY, *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    tail = [l for l in (p.stdout or "").splitlines() if l.strip()]
    return p.returncode, (tail[-1] if tail else "")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
