// SPDX-License-Identifier: Apache-2.0

//! The canonical ABI types for `qqq:http`.
//!
//! # Why these are hand-written rather than generated by `bindgen!`
//!
//! `bindgen!` generates a whole world's bindings, including every import a guest
//! may use and the export traits it implements. The host needs none of that: it
//! calls **one** export with **one** signature, and a generated world would also
//! generate every capability interface the manifest might grant — putting the
//! host's own view of a guest's imports into the host's type system, which is
//! exactly the coupling `linker.rs` avoids by building from grants alone.
//!
//! What the host does need is that its Rust types match the WIT types
//! **exactly**, because `Lower`/`Lift` are derived structurally: a field of the
//! wrong type is a runtime type-check failure, not a compile error. So the types
//! below mirror `wit/qqq-http.wit` field for field, and the tests below pin the
//! parts a type checker cannot see — the **variant order**, which is the wire
//! encoding.

use wasmtime::component::{ComponentType, Lift, Lower};

/// The HTTP methods `qqq:http/method` declares, in the WIT's own order.
///
/// # Why the order matters and is asserted
///
/// A WIT `enum` lowers to a **case index**, so reordering these variants silently
/// renumbers every method: `post` would arrive as `put`. The order is the WIT
/// file's, and the test below pins it — because the failure mode here is a
/// request routed to the wrong handler, which no type checker can see.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ComponentType, Lower, Lift)]
#[component(enum)]
#[repr(u8)]
pub enum Method {
    /// `GET` — a safe, idempotent read.
    #[component(name = "get")]
    Get,
    /// `HEAD` — like `GET`, with no body.
    #[component(name = "head")]
    Head,
    /// `POST` — submit, typically non-idempotent.
    #[component(name = "post")]
    Post,
    /// `PUT` — replace a resource.
    #[component(name = "put")]
    Put,
    /// `DELETE` — remove a resource.
    #[component(name = "delete")]
    Delete,
    /// `CONNECT` — establish a tunnel.
    ///
    /// Present because the manifest's method set includes it
    /// (`qqq_cap::manifest::METHODS`). `qqqai openapi` **refuses** a route
    /// declaring it, because `OpenAPI` 3.0 has no operation object for it.
    #[component(name = "connect")]
    Connect,
    /// `OPTIONS` — describe the communication options.
    #[component(name = "options")]
    Options,
    /// `TRACE` — echo the request.
    #[component(name = "trace")]
    Trace,
    /// `PATCH` — apply a partial modification.
    #[component(name = "patch")]
    Patch,
}

impl Method {
    /// Every variant, in ABI order.
    pub const ALL: [Self; 9] = [
        Self::Get,
        Self::Head,
        Self::Post,
        Self::Put,
        Self::Delete,
        Self::Connect,
        Self::Options,
        Self::Trace,
        Self::Patch,
    ];

    /// The WIT spelling.
    #[must_use]
    pub const fn as_wit_str(self) -> &'static str {
        match self {
            Self::Get => "get",
            Self::Head => "head",
            Self::Post => "post",
            Self::Put => "put",
            Self::Delete => "delete",
            Self::Connect => "connect",
            Self::Options => "options",
            Self::Trace => "trace",
            Self::Patch => "patch",
        }
    }

    /// Parse a WIT spelling.
    ///
    /// `None` for an unknown method rather than a default, because defaulting a
    /// method turns a typo into a request the guest answers with the wrong verb.
    #[must_use]
    pub fn from_wit_str(s: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|m| m.as_wit_str() == s)
    }
}

/// `qqq:http/header` — a name and its raw byte value.
///
/// The value is bytes, not a `String`, because a header value is not guaranteed
/// UTF-8 and a host that forced it would mangle a valid request.
#[derive(Debug, Clone, PartialEq, Eq, ComponentType, Lower, Lift)]
#[component(record)]
pub struct Header {
    /// The header name.
    pub name: String,
    /// The header value, raw.
    pub value: Vec<u8>,
}

/// `qqq:http/request`.
#[derive(Debug, Clone, PartialEq, Eq, ComponentType, Lower, Lift)]
#[component(record)]
pub struct Request {
    /// The method.
    pub method: Method,
    /// The full URL. The host parses it; a guest cannot smuggle a different host
    /// past the allowlist by crafting the authority section.
    pub url: String,
    /// The headers.
    pub headers: Vec<Header>,
    /// `option<list<u8>>`: `None` and `Some(vec![])` are **different** on the
    /// wire and mean different things — absent versus empty.
    pub body: Option<Vec<u8>>,
}

/// `qqq:http/response`.
#[derive(Debug, Clone, PartialEq, Eq, ComponentType, Lower, Lift)]
#[component(record)]
pub struct Response {
    /// The status code.
    pub status: u16,
    /// The headers.
    pub headers: Vec<Header>,
    /// The body.
    pub body: Vec<u8>,
}

/// `qqq:http/http-error` — the **guest's** vocabulary for why it could not answer.
///
/// Distinct from [`crate::invoke::Failure`], which is the host's. See that type
/// for why conflating them sends an operator to the wrong cause.
///
/// The variant order is the WIT file's, for the same reason [`Method`]'s is.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ComponentType, Lower, Lift)]
#[component(enum)]
#[repr(u8)]
pub enum HttpError {
    /// The host is not on the manifest's egress allowlist.
    #[component(name = "host-not-allowed")]
    HostNotAllowed,
    /// The connection failed or timed out.
    #[component(name = "connection-failed")]
    ConnectionFailed,
    /// The request exceeded the manifest's size cap.
    #[component(name = "request-too-large")]
    RequestTooLarge,
    /// The response exceeded the manifest's size cap.
    #[component(name = "response-too-large")]
    ResponseTooLarge,
    /// The URL was malformed.
    #[component(name = "invalid-url")]
    InvalidUrl,
    /// The per-instance subrequest budget is exhausted.
    #[component(name = "subrequest-limit-exceeded")]
    SubrequestLimitExceeded,
}

impl HttpError {
    /// Every variant, in ABI order.
    pub const ALL: [Self; 6] = [
        Self::HostNotAllowed,
        Self::ConnectionFailed,
        Self::RequestTooLarge,
        Self::ResponseTooLarge,
        Self::InvalidUrl,
        Self::SubrequestLimitExceeded,
    ];

    /// The WIT spelling, kebab-cased.
    #[must_use]
    pub const fn as_wit_str(self) -> &'static str {
        match self {
            Self::HostNotAllowed => "host-not-allowed",
            Self::ConnectionFailed => "connection-failed",
            Self::RequestTooLarge => "request-too-large",
            Self::ResponseTooLarge => "response-too-large",
            Self::InvalidUrl => "invalid-url",
            Self::SubrequestLimitExceeded => "subrequest-limit-exceeded",
        }
    }

    /// A human explanation, for a log line.
    #[must_use]
    pub const fn human_message(self) -> &'static str {
        match self {
            Self::HostNotAllowed => {
                "the guest is not permitted to reach that host (a policy denial, \
                 not a network failure)"
            }
            Self::ConnectionFailed => "the connection failed or timed out",
            Self::RequestTooLarge => "the request exceeded the manifest's size cap",
            Self::ResponseTooLarge => "the response exceeded the manifest's size cap",
            Self::InvalidUrl => "the URL was malformed",
            Self::SubrequestLimitExceeded => "the per-instance subrequest budget is exhausted",
        }
    }
}

impl std::fmt::Display for HttpError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_wit_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_method_order_is_the_abi_order() {
        // A WIT enum lowers to a case index, so this list IS the wire encoding.
        // Reordering it renumbers every method silently.
        let index: Vec<&str> = Method::ALL.iter().map(|m| m.as_wit_str()).collect();
        assert_eq!(
            index,
            vec!["get", "head", "post", "put", "delete", "connect", "options", "trace", "patch"]
        );
    }

    #[test]
    fn the_error_order_is_the_abi_order() {
        let index: Vec<&str> = HttpError::ALL.iter().map(|e| e.as_wit_str()).collect();
        assert_eq!(
            index,
            vec![
                "host-not-allowed",
                "connection-failed",
                "request-too-large",
                "response-too-large",
                "invalid-url",
                "subrequest-limit-exceeded"
            ]
        );
    }

    #[test]
    fn every_method_round_trips_through_its_wit_spelling() {
        for m in Method::ALL {
            assert_eq!(
                Method::from_wit_str(m.as_wit_str()),
                Some(m),
                "`{}` must round-trip",
                m.as_wit_str()
            );
        }
    }

    #[test]
    fn an_unknown_method_is_none_rather_than_a_default() {
        // Defaulting would turn a typo into a request the guest answers with the
        // wrong verb -- silently, and only in production.
        assert_eq!(Method::from_wit_str("GTE"), None);
        assert_eq!(
            Method::from_wit_str("GET"),
            None,
            "the WIT spelling is lower-case"
        );
        assert_eq!(Method::from_wit_str(""), None);
    }

    #[test]
    fn a_denial_does_not_read_as_a_network_failure() {
        // The distinction the WIT file itself makes: a guest that cannot tell
        // "I may not reach that host" from "that host is down" retries forever
        // against a policy denial.
        let msg = HttpError::HostNotAllowed.human_message();
        assert!(msg.contains("policy denial"), "a denial must say so: {msg}");
        assert!(
            !msg.contains("timed out"),
            "a denial must not read as a network failure: {msg}"
        );
    }

    #[test]
    fn every_error_has_a_non_empty_message() {
        for e in HttpError::ALL {
            assert!(
                !e.human_message().is_empty(),
                "`{}` needs one",
                e.as_wit_str()
            );
        }
    }

    #[test]
    fn the_error_display_is_the_wit_spelling() {
        assert_eq!(HttpError::InvalidUrl.to_string(), "invalid-url");
    }
}
